---
- hosts: all
  become: true
  vars_files:
     - rhel7-base.yml

  pre_tasks:
    
    - name: Updating System Packages Before Ansible Run
      yum:
        name: '*'
        state: latest
    - name: Set timezone to Europe/London
      community.general.timezone:
        name: Europe/London

  roles:
    - epel
    - ch_collections.base.pip
    - ch_collections.base.os_package_control
    - ch_collections.base.rhel7_cis
    - ch_collections.base.clamav
    - cloudwatch-agent
    - ch_collections.base.cloudwatch_agent_helper
    - ch_collections.base.auditd
    - ch_collections.security_banner.banner
    
  tasks:
    - name: update iscsi config setting
      lineinfile: 
        path: /etc/iscsi/iscsid.conf
        regexp: '^node.session.timeo.replacement_timeout = 120' 
        line: 'node.session.timeo.replacement_timeout = 5'
        backrefs: yes

    - name: Run multipath config tool to enable multipath and disable user friendly names
      command: mpathconf --enable --with_multipathd y --user_friendly_names n
      args:
        creates: /etc/multipath.conf

    - name: Make sure aws ssm agent is enabled
      service:
        name: amazon-ssm-agent
        state: stopped
        enabled: yes

    - name: Create persistent SELinux boolean policies
      ansible.posix.seboolean:
        name: "{{ item }}"
        state: yes
        persistent: yes
      loop: "{{ selinux_policies }}"

    - name: service chronyd
      service:
        name: chronyd
        state: started
        enabled: yes

    - name: Restrict Kernel log access
      block:
        - name: Copy kernel hardening file
          ansible.builtin.copy:
            src: 10-kernel-hardening.conf
            dest: /etc/sysctl.d/10-kernel-hardening.conf
            owner: root
            group: root
            mode: '0600'
            
        - name: Update Kernel Parameters
          command: sysctl -p        

        
