## Install firewalld Package

- name: Ensure firewalld is installed
  package:
    name: firewalld
    state: present

- name: Gather the package facts
  package_facts:
    manager: auto

## Verify firewalld Enabled

- name: Enable and start firewalld service if installed and not in a container
  block:
    - name: Enable firewalld service
      systemd:
        name: firewalld
        enabled: yes
        state: started
        masked: no
  when:
    - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"]
    - '"firewalld" in ansible_facts.packages'
